name: ps_games
description: PlayStation games concept
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 1.1.1+1
  google_fonts: 3.0.1
  provider: 6.0.3

dev_dependencies:
  build_runner: 2.1.11
  flutter_gen_runner: 4.2.1
  very_good_analysis: 3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/games/
    - assets/symbols/
    - assets/svg/
    - assets/google_fonts/
